fix: unhandled rejection in Loader.image()
oslllo/potrace pull request #46
Opened 2021-12-27 09:37 UTC by OpenGG

Loader.image() creates promise with async init function.

When [jimp.read()](https://github.com/oslllo/potrace/blob/6623028dcbd3ab8485d17350e8fb13eceace5866/src/loader.js#L24) throws, it will be async error, which cannot caught by [new Promise()](https://github.com/oslllo/potrace/blob/6623028dcbd3ab8485d17350e8fb13eceace5866/src/loader.js#L13).

I refactored Loader.image() into async function, making sure the error will be thrown and caught by caller.

Remaining issue: What should be done with element.onerror(), if any ?

2021-12-28 09:18 UTC, Ghustavh97 commented
@OpenGG Thanks for this, do you mind writing a test case for this?

2021-12-28 10:02 UTC, Ghustavh97 requested changes

2021-12-28 10:02 UTC, Ghustavh97 commented on src/loader.js
> +            file: image,
Looks like the image variable is undefined. Failing tests

2021-12-28 10:02 UTC, Ghustavh97 commented on src/loader.js
> +        var element = await base64ToImage(this.document, base64);
Pass image variable here

2021-12-30 12:14 UTC, OpenGG commented
@Ghustavh97 code fixed with according test case

2021-12-30 14:17 UTC, Ghustavh97 approved these changes
Looks good, thanks for the fix

2021-12-30 14:20 UTC, Ghustavh97 commented
> Remaining issue: What should be done with element.onerror(), if any ?

I remember trying to make it throw an error so I could write a test case for it but failed. If you can make it fail then feel free to open another PR with the fix.

2021-12-30 14:20 UTC, merged